#Write a function ‘mutate’ to compute all words generated by a single mutation on a
#given word. A mutation is defined as inserting a character, deleting a character,
#replacing a character, or swapping 2 consecutive characters in a string. For simplicity
#consider only letters from a to z.


def mutate(word):
    return {
        value
        for i in range(len(word))
        for letter in 'abcdefghijklmnopqrstuvwxyz'
        for value in [
        word[:i] + word[i + 1:],          # remove
        word[:i] + letter + word[i:],     # insert
        word[:i] + letter + word[i + 1:], # replace
        word[:i] + word[i + 1: i + 2] + word[i:i + 1] + word[i + 2:]
        ]
    }

print(mutate("ab"))